"""
Add test types

Revision ID: e6920ba1c709
Revises: 4348f41a6094
Create Date: 2025-10-06 10:12:43.132489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6920ba1c709"
down_revision: Union[str, Sequence[str], None] = "4348f41a6094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    enum_name = "testtype"

    new_values = [
        "strength_after_1_hour",
        "strength_after_3_hours",
        "strength_after_24_hours",
        "gas_forming_property"
    ]

    for value in new_values:
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{value}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
